In [26]:
import tensorflow as tf
import numpy as np

from keras.layers import Conv2D
from keras import Model, Sequential

In [27]:
input_shape = (1, 4, 3, 3)
x = tf.random.normal(input_shape)

x

<tf.Tensor: shape=(1, 4, 3, 3), dtype=float32, numpy=
array([[[[-0.24598129,  1.7733613 ,  0.52840036],
         [-1.6848425 , -0.39541468,  0.94612634],
         [ 0.02833155,  0.78498316,  0.00956134]],

        [[ 0.81568474,  2.2247176 ,  0.50566477],
         [-0.45887318, -1.3251251 ,  0.563656  ],
         [-0.42146704, -0.15216543, -0.7614754 ]],

        [[ 0.9322777 ,  1.2336996 ,  0.8780712 ],
         [ 0.06405106, -0.07501785, -0.6313727 ],
         [-0.7100054 , -0.87229365,  0.7717652 ]],

        [[ 0.8471736 , -0.81116426, -0.53608674],
         [ 1.5254331 , -1.116241  ,  0.46301606],
         [-1.1061062 ,  1.3173728 ,  0.85378504]]]], dtype=float32)>

In [28]:
arr = np.array([1,2,3,4,5,6,7])

print(np.random.choice(25,3))

print(arr[[0,2,4]])

print(np.dot([[1,0,0],[0,1,0]], [1,2,3]))

arr2 = np.zeros((5,5))
print(arr2[1,2])


[8 8 4]
[1 3 5]
[1 2]
0.0


In [63]:
from keras import Sequential, Model
from keras.layers import Embedding, GlobalAveragePooling1D, Dense, concatenate, Input
import numpy as np

input1 = Input(shape=(27, 27), batch_size=5)
dense1 = Dense(300, activation='relu', name='layer_1')(input1)
input2 = Input(shape=(27, 27), batch_size=5)
dense2 = Dense(300, activation='relu', name='layer_2')(input2)
merged = concatenate([dense1, dense2])
out = Dense(1, activation='softmax', name='output_layer')(merged)
model = Model(inputs = [input1, input2], outputs = [out])


i1 = np.random.randint(0,10, (5, 27,27))
i2 = np.random.randint(0,10, (5, 27,27))

print(model.predict([i1,i2]))

print(i1)


[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]]
[[[7 6 0 ... 6 5 1]
  [3 4 8 ... 4 5 2]
  [7 

In [ ]:
checkpoint = ModelCheckpoint('nn_memory/weights.h5', monitor='val_acc',
        save_best_only=True, verbose=2)
        early_stopping = EarlyStopping(monitor="val_loss", patience=5)